### ISSUE TITLE
resize POST call?

### ISSUE THREAD

**Issue by elixx** [os-js/osjs-xterm-application#16]
I'm running down an issue that I thought was originally due to CloudFlare (524 request time limit exceeded) but now I am seeing the same thing direct to nginx (502 error from nginx) or direct to the `npm serve` process on :8000. There is a POST to .../resize that never seems to complete:

![image](https://user-images.githubusercontent.com/2325870/83157516-b136f780-a0d1-11ea-8a8a-af3679b3058c.png)

Any guidance would be appreciated

**Comment by elixx** [comment]
To reproduce would be to spawn an Xterm and resize the window.

**Comment by andersevenrud** [comment]
Hi, and thanks!

Seems like the endpoint works, but it does not respond with anything :facepalm: 

https://github.com/os-js/osjs-xterm-application/blob/master/server.js#L149

Ideally it should just send `OK` with a 200 or something.

**Comment by andersevenrud** [comment]
I published an update to npm that should fix this issue. Run `npm update @osjs/xterm-application` and restart the server :)

Thanks for reporting!

**Comment by elixx** [comment]
Awesome, that works great, and fixes that bug although didn't resolve the problem I was originally running down.
Could we have ping / keepalive on the Xterm websocket, as well?

**Comment by andersevenrud** [comment]
> Could we have ping / keepalive on the Xterm websocket, as well?

Feel free to open up an issue about this. Should be fairly simple to implement :)
